version: '3.7'

services:
  nginx-php-test:
    container_name: nginx-php-test
    image: carlonicora/nginx-php-test:1.17
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html:delegated
      - ../logs/nginx:/logs/nginx:delegated
    networks:
      - default_network
  php-test:
    container_name: php-test
    image: carlonicora/php-php-test:7.3.9
    restart: always
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ../:/var/www/html:delegated
    networks:
      - default_network
  mysql-php-test:
    container_name: mysql-php-test
    image: mysql:8.0
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
    ports:
      - "3306:3306"
    volumes:
      - ../data:/var/lib/mysql:delegated
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
    name: privateNetwork